DROP TABLE IF EXISTS ARTYSTA;

DROP TABLE IF EXISTS EKSPONAT;

DROP TABLE IF EXISTS GALERIA;

DROP TABLE IF EXISTS HISTORIA_MAGAZYNOWANIA;

DROP TABLE IF EXISTS HISTORIA_WYPOZYCZEN;

DROP TABLE IF EXISTS HISTORIA_WYSTAW;

DROP TABLE IF EXISTS INSTYTUCJA;

DROP TABLE IF EXISTS MAGAZYN;

-- Table: Artysta
CREATE TABLE ARTYSTA (
    ID INTEGER PRIMARY KEY,
    IMIE VARCHAR(20) NOT NULL,
    NAZWISKO VARCHAR(30) NOT NULL,
    ROK_URODZENIA INTEGER NOT NULL,
    ROK_SMIERCI INTEGER
);

-- Table: Eksponat
CREATE TABLE EKSPONAT (
    ID INTEGER PRIMARY KEY,
    TYTUL VARCHAR(50),
    TYP VARCHAR(30) NOT NULL,
    WYSOKOSC NUMERIC(10, 3) CHECK (WYSOKOSC > 0) NOT NULL,
    SZEROKOSC NUMERIC(10, 3) CHECK (SZEROKOSC > 0) NOT NULL,
    WAGA NUMERIC(10, 3) CHECK (WAGA > 0) NOT NULL,
    CZY_NAJCENNIEJSZY BOOLEAN NOT NULL,
    ARTYSTA_ID INTEGER,
    CONSTRAINT EKSPONAT_PK PRIMARY KEY (ID)
);

-- Table: Galeria
CREATE TABLE GALERIA (
    IDENTYFIKATOR INTEGER PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL,
    MIASTO VARCHAR(40) NOT NULL
);

-- Table: Historia_magazynowania
CREATE TABLE HISTORIA_MAGAZYNOWANIA (
    ID SERIAL PRIMARY KEY,
    DATA_ROZPOCZECIA DATE NOT NULL,
    DATA_ZAKONCZENIA DATE NULL,
    CEL VARCHAR(40) NOT NULL,
    MAGAZYN_IDENTYFIKATOR INTEGER NOT NULL REFERENCES MAGAZYN,
    EKSPONAT_ID INTEGER NOT NULL REFERENCES EKSPONAT
);

-- Table: Historia_wypozyczen
CREATE TABLE HISTORIA_WYPOZYCZEN (
    ID SERIAL PRIMARY KEY,
    DATA_WYPOZYCZENIA DATE NOT NULL,
    DATA_ZWROTU DATE,
    EKSPONAT_ID INTEGER NOT NULL REFERENCES EKSPONAT,
    INSTYTUCJA_IDENTYFIKATOR INTEGER NOT NULL REFERENCES INSTYTUCJA
);

-- Table: Historia_wystaw
CREATE TABLE HISTORIA_WYSTAW (
    ID SERIAL PRIMARY KEY,
    DATA_ROZPOCZECIA DATE NOT NULL,
    DATA_ZAKONCZENIA DATE,
    NR_SALI INTEGER NOT NULL,
    EKSPONAT_ID INTEGER NOT NULL REFERENCES EKSPONAT,
    GALERIA_IDENTYFIKATOR INTEGER NOT NULL REFERENCES GALERIA
);

-- Table: Instytucja
CREATE TABLE INSTYTUCJA (
    IDENTYFIKATOR INTEGER NOT NULL,
    NAZWA VARCHAR(50) NOT NULL,
    MIASTO VARCHAR(40) NOT NULL
);

-- Table: Magazyn
CREATE TABLE MAGAZYN (
    IDENTYFIKATOR INTEGER NOT NULL,
    MIASTO VARCHAR(40) NOT NULL
);